---
title: "Experiment with DDA"
output: 
  html_document:
    theme: lumen
---
```{r global.infos, echo=FALSE}

# risk aversion scores
# 0-1 : highly risk loving
#  2  : very risk loving
#  3  : risk loving
#  4  : risk neutral
#  5  : slightly risk averse
#  6  : risk averse
#  7  : very risk averse
#  8  : highly risk avers
# 9-10 : max choix sûr

# self efficacy scores
# 0 : not a player so did not answer
# de 10 à 20 : sentiment AE faible
# de 21 à 30 : sentiment AE moyen
# de 31 à 40 : sentiment AE fort
# de 41 à 50 : sentiment AE très fort

```

```{r setup, include = FALSE}
#------------------------------------------------------
#                  SETUP : PACKAGES
#------------------------------------------------------

require(xlsx)
require(plyr)
require(data.table)
require(ggplot2)
library(car)
require(lme4)
require(lmerTest)
require(Matrix)
library(usdm)
require(lattice)
require(psychometric)
require(MuMIn)
require(pyramid)
require(sjPlot)
require(arm)

#------------------------------------------------------
#              SETUP : UTILS FUNCTIONS
#------------------------------------------------------
format.pval.stars <- function(pv){
  pv = signif(pv,digits=2)
  if(pv<0.001) {
    return(paste(pv,"***"));
  }else if(pv<0.01){ 
    return(paste(pv,"**"));
  }else  if(pv<0.05){ 
    return(paste(pv,"*"));
  }else if(pv<0.1){ 
    return(paste(pv,"."));
  }else{
    return(paste(pv,":("));
  }
  return("unable to format pvalue !!");
}

format.coef <- function(coef,p.val){
  return(paste(signif(coef,digits=3),format.pval.stars(p.val)))
}

remove.na.cols <- function(DT){
  return(as.data.table(DT[,which(unlist(lapply(DT, function(x)!all(is.na(x))))),with=F]))
}
remove.na.rows <- function(DT){
  return(as.data.table(DT[rowSums(is.na(DT)) != ncol(DT),]))
}
set.empty.to.na <- function(DT){
  return(as.data.table(lapply(DT, function(x){replace(x, x=="",NA)})))
}

remove.head.tail <- function(DT,nb,bHead=TRUE){
  DT <- as.data.table(DT)
  setkey(DTLoc, IDjoueur, nom_du_jeu, action_de_jeu)
  if(bHead)
    DT <- DTLoc[, tail(.SD, nrow(.SD)-nb), by = .(IDjoueur,nom_du_jeu)]
  else
    DT <- DTLoc[, head(.SD, nrow(.SD)-nb), by = .(IDjoueur,nom_du_jeu)]
  return(DT)
}
```

```{r data.loading, echo=FALSE}
#------------------------------------------------------
#                  LOADING DATA
#------------------------------------------------------

# Data from game trace
fileGameTrace = "./log_thomas_XPFINALES_WEEK2.txt"
DTGame <- read.csv(fileGameTrace,header=TRUE,sep=";")
DTGame <- as.data.table(DTGame)
DTGame <- set.empty.to.na(DTGame)
DTGame <- remove.na.cols(DTGame)
DTGame <- remove.na.rows(DTGame)

# Data from questionnaire
fileQuestions = "./log_questionnaire_XP_WEEK2_REWRITED.csv"
DTQuest <- read.csv(fileQuestions,header=TRUE,sep=";")
DTQuest <- as.data.table(DTQuest)
DTQuest <- set.empty.to.na(DTQuest)
DTQuest <- remove.na.cols(DTQuest)
DTQuest <- remove.na.rows(DTQuest)

# Merging tables into one
setkey(DTGame,IDjoueur)
setkey(DTQuest,IDjoueur)
DTAll <- merge(DTGame,DTQuest, all.x=TRUE)
```


```{r questionnaire.variables, echo=FALSE}
#------------------------------------------------------
#         ADDING VARIABLES FOR QUESTIONNAIRE
#------------------------------------------------------

# how much playing video games in general
DTAll$play.video.games = pmax(DTAll$profilJoueur2,
                              DTAll$profilJoueur3,
                              DTAll$profilJoueur4,
                              DTAll$profilJoueur5,
                              DTAll$profilJoueur6)

# how much playing board games
DTAll$play.board.game = pmax(DTAll$profilJoueur1)

# how much playing games with money
DTAll$play.money.games = pmax(DTAll$profilJoueur7)

# feeling of self efficacy
cols.self.eff <- c("autoEffJoueur1","autoEffJoueur2","autoEffJoueur3","autoEffJoueur4",
                   "autoEffJoueur5","autoEffJoueur6","autoEffJoueur7","autoEffJoueur8",
                   "autoEffJoueur9","autoEffJoueur10")
DTAll = DTAll[, self.eff := rowSums(.SD,na.rm=TRUE), .SDcols = cols.self.eff]

# risk aversion

cols.risk.av <- c("loterie1","loterie2","loterie3","loterie4","loterie5",
                  "loterie6","loterie7","loterie8","loterie9","loterie10")
DTAll = DTAll[, risk.av := rowSums(.SD,na.rm=TRUE), .SDcols = cols.risk.av]
```

```{r game.traces.simple.variables, echo=FALSE}
#------------------------------------------------------
#         ADDING SIMPLE VARIABLES FOR GAME TRACES
#------------------------------------------------------

DTAll$perdant <- 1-DTAll$gagnant # if the player did fail on that try
DTAll$miseNorm <- DTAll$mise / 7 # normalize bet
 
#number of consecutive fails
gagnant = DTAll$gagnant; # tmp vector faster to read
id = DTAll$IDjoueur; # tmp vector faster to read
nbFails <- numeric(nrow(DTAll)) # tmp vector faster to write
nbFails[1] = 0;
nbFailCpt = 0;
lastID <- id[1];
for(i in 2:nrow(DTAll)){
  if(id[i] != lastID){
    nbFailCpt = 0;
  }else{
    if(gagnant[i-1] == 0){
      nbFailCpt = nbFailCpt+1;
    }else{
      nbFailCpt = 0;
    }
  }
  nbFails[i] <- nbFailCpt;
  lastID = id[i-1];
}
  
DTAll$nbFail = nbFails;

#number of consecutive wins
nbWins <- numeric(nrow(DTAll)) # tmp vector faster to write
nbWins[1] = 0;
nbWinCpt = 0;
lastID <- id[1];
for(i in 2:nrow(DTAll)){
  if(id[i] != lastID){
    nbWinCpt = 0;
  }else{
    if(gagnant[i-1] == 1){
      nbWinCpt = nbWinCpt+1;
    }else{
      nbWinCpt = 0;
    }
  }
  nbWins[i] <- nbWinCpt;
  lastID = id[i-1];
}
  
DTAll$nbWin = nbWins;

#sum of absolute bet variation over time, mainly to spot 1/7/1/7/1/7 behaviors
mise = DTAll$mise;
cumulDeltaMise <- numeric(nrow(DTAll))
cumulDeltaMise[1] = 0;
lastID <- id[1];
currentCumulDeltaMise = 0;
for(i in 2:nrow(DTAll)){
  if(id[i] != lastID){
    currentCumulDeltaMise = 0;
  }else{
    currentCumulDeltaMise = currentCumulDeltaMise + abs(mise[i] - mise[i-1]);
  }
  lastID = id[i];
  cumulDeltaMise[i] = currentCumulDeltaMise;
}

DTAll$cumulDeltaMise = cumulDeltaMise;
```

# Removing Outliers

```{r removing.outliers.setup, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS SETUP
#------------------------------------------------------

DTM <- DTAll[which(DTAll$nom_du_jeu=="Motrice"),]
DTL <- DTAll[which(DTAll$nom_du_jeu=="Logique2"),]
DTS <- DTAll[which(DTAll$nom_du_jeu=="Sensoriel"),]


get.outliers <- function(DTDescMLoc,DTDescSLoc,DTDescLLoc){
  outliersM <- boxplot.stats(DTDescMLoc$var)$out
  outliersS <- boxplot.stats(DTDescSLoc$var)$out
  outliersL <- boxplot.stats(DTDescLLoc$var)$out
  
  outliers = data.table(type=character(0),id=character(0))
  setkey(outliers,id)
  if(length(outliersM) > 0)
    outliers = merge(outliers,data.table(id=DTDescMLoc[var %in% outliersM]$IDjoueur,type="Moteur"),by=c("id","type"),all=TRUE)
  if(length(outliersS) > 0)
    outliers = merge(outliers,data.table(id=DTDescSLoc[var %in% outliersS]$IDjoueur,type="Sensoriel"),by=c("id","type"),all=TRUE)
  if(length(outliersL) > 0)
    outliers = merge(outliers,data.table(id=DTDescLLoc[var %in% outliersL]$IDjoueur,type="Logique"),by=c("id","type"),all=TRUE)
    
  return(outliers)
}

plot.outliers <- function(DT,title){
  p <- ggplot(DT, 
            aes(type,var)) + 
            xlab("Difficulty Type") + 
            ylab(title)
  p <- p + geom_boxplot() + geom_point(shape=1) 
  print(p)
}
```

```{r detect.outliers.bet.sd, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS BET STD DEV
#------------------------------------------------------
DTDescM = DTM[,.(type="Moteur",var=sd(miseNorm)),by=IDjoueur]
DTDescS = DTS[,.(type="Sensoriel",var=sd(miseNorm)),by=IDjoueur]
DTDescL = DTL[,.(type="Logique",var=sd(miseNorm)),by=IDjoueur]

plot.outliers(rbind(DTDescM,rbind(DTDescL,DTDescS)), "Bet Standard Dev");

outliers = get.outliers(DTDescM,DTDescS,DTDescL)
print(paste("Outliers :",toString(outliers$id)))
```

```{r detect.outliers.bet.mean, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS BET MEAN
#------------------------------------------------------
DTDescM = DTM[,.(type="Moteur",var=mean(miseNorm)),by=IDjoueur]
DTDescS = DTS[,.(type="Sensoriel",var=mean(miseNorm)),by=IDjoueur]
DTDescL = DTL[,.(type="Logique",var=mean(miseNorm)),by=IDjoueur]

plot.outliers(rbind(DTDescM,rbind(DTDescL,DTDescS)), "Bet Mean");

outliersLoc = get.outliers(DTDescM,DTDescS,DTDescL)
outliers = merge(outliers,outliersLoc,by=c("id","type"),all=TRUE)

print(paste("Outliers :",toString(outliersLoc$id)))
```

```{r detect.outliers.win.sum, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS SUM OF WINS
#------------------------------------------------------
# Difficulty : win sum
DTDescM = DTM[,.(type="Moteur",var=sum(gagnant)),by=IDjoueur]
DTDescS = DTS[,.(type="Sensoriel",var=sum(gagnant)),by=IDjoueur]
DTDescL = DTL[,.(type="Logique",var=sum(gagnant)),by=IDjoueur]

plot.outliers(rbind(DTDescM,rbind(DTDescL,DTDescS)), "Win Sum");

outliersLoc = get.outliers(DTDescM,DTDescS,DTDescL)
outliers = merge(outliers,outliersLoc,by=c("id","type"),all=TRUE)
print(paste("Outliers :",toString(outliersLoc$id)))
```
```{r detect.outliers.sheeps.saved, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS SAVED SHEEPS
#------------------------------------------------------
# Difficulty and strategy = saved sheeps
DTDescM = DTM[,.(type="Moteur",var=max(moutons_sauves)),by=IDjoueur]
DTDescS = DTS[,.(type="Sensoriel",var=max(moutons_sauves)),by=IDjoueur]
DTDescL = DTL[,.(type="Logique",var=max(moutons_sauves)),by=IDjoueur]

plot.outliers(rbind(DTDescM,rbind(DTDescL,DTDescS)), "Saved sheeps");

outliersLoc = get.outliers(DTDescM,DTDescS,DTDescL)
outliers = merge(outliers,outliersLoc,by=c("id","type"),all=TRUE)
print(paste("Outliers :",toString(outliersLoc$id)))
```

```{r detect.outliers.dda.exploit, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS EXPLOIT DDA
#------------------------------------------------------
# DDA Exploit : Win/Fail delta sum max
DTDescM = DTM[,.(type="Moteur",var=max(cumulDeltaMise)),by=IDjoueur]
DTDescS = DTS[,.(type="Sensoriel",var=max(cumulDeltaMise)),by=IDjoueur]
DTDescL = DTL[,.(type="Logique",var=max(cumulDeltaMise)),by=IDjoueur]

plot.outliers(rbind(DTDescM,rbind(DTDescL,DTDescS)), "Win/Fail delta sum max");

outliersLoc = get.outliers(DTDescM,DTDescS,DTDescL)
outliers = merge(outliers,outliersLoc,by=c("id","type"),all=TRUE)
print(paste("Outliers :",toString(outliersLoc$id)))
```

```{r detect.outliers.summary, echo=FALSE}
#------------------------------------------------------
#            OUTLIERS SUMMARY
#------------------------------------------------------
print(paste("Total number of outliers: ",toString(nrow(unique(outliers,by="id")))))
print(paste("Total number of outliers motor task: ",toString(nrow(unique(outliers[type=="Moteur"],by="id")))))
print(paste("Total number of outliers perceptive task: ",toString(nrow(unique(outliers[type=="Logique"],by="id")))))
print(paste("Total number of outliers logical task: ",toString(nrow(unique(outliers[type=="Sensoriel"],by="id")))))
```

```{r remove.outliers, echo=FALSE}
#------------------------------------------------------
#            REMOVING OUTLIERS FROM TABLES
#------------------------------------------------------
# removing all outliers
DTM <- DTM[!IDjoueur %in% unlist(outliers[type=="Moteur"]$id)]
DTS <- DTS[!IDjoueur %in% unlist(outliers[type=="Sensoriel"]$id)]
DTL <- DTL[!IDjoueur %in% unlist(outliers[type=="Logique"]$id)]
DTAll <- data.table()
DTAll <- rbind(DTAll,DTL)
DTAll <- rbind(DTAll,DTM)
DTAll <- rbind(DTAll,DTS)
```

```{r modeling.difficulty.compute.utils, echo=FALSE}
#------------------------------------------------------
#            MODELING OBJECTIVE DIFFICULTY 
#------------------------------------------------------
#modeling difficulty as mixed effect linear model
model.objective.diff <- function(DT){
  return(glmer(perdant ~ difficulty + (1 | IDjoueur), data=DT,family = "binomial"(link = "logit")))
  
}

add.diff.obj <- function (DT,fit){
  sample = data.frame(difficulty=DT$difficulty, IDjoueur=DT$IDjoueur)
  DT$obj.diff =  predict(fit, newdata = sample, type = "response")
  return (DT)
}

get.levels <- function(DT,fit){
  fit.ranef = ranef(fit)$IDjoueur
  DTLevel <- data.table(IDjoueur=rownames(fit.ranef),niveau=-fit.ranef); # ! minus, cause it's a level
  setnames(DTLevel,"niveau.(Intercept)","niveau")
  return(DTLevel)
}

add.levels <- function(DT,fit){
  DTLevel <- get.levels(DT,fit)
  return(merge(DT,DTLevel,by="IDjoueur",all=T))
} 
```

```{r modeling.difficulty.draw.utils, echo=FALSE}
#------------------------------------------------------
#         SHOWING OBJECTIVE DIFFICULTY 
#------------------------------------------------------
print.objective.diff.model <- function (DT,fit) {
  fit.ranef = ranef(fit)$IDjoueur
  fit.sum = unlist(summary(fit))
  inter = fit.sum$coefficients1
  beta.diff = fit.sum$coefficients2
  inter.p.val = fit.sum$coefficients7
  beta.diff.p.val = fit.sum$coefficients8
  fit.r.value = r.squaredGLMM(fit)[2] #R2 for mixed effect model
  
  print(table(DT$nom_du_jeu))
  print("Player levels from ranef:")
  print(summary(fit.ranef))
  print(paste("Intercept:",format.coef(inter,inter.p.val)))
  print(paste("Difficulty:",format.coef(beta.diff,beta.diff.p.val)))
  print(paste("R2:",signif(fit.r.value,digits=3)))
}

plot.objective.diff.model.curves <- function (DT,fit) {

  DTLevel <- get.levels(DT,fit)
  
  for(i in 1:nrow(DTLevel)){
    sample = data.frame(difficulty=seq(0, 1, 0.05),IDjoueur=DTLevel[i]$IDjoueur)
    newres = predict(fit, newdata = sample, type = "response")
    DT = data.table(difficulty=seq(0, 1, 0.05),IDjoueur = DTLevel[i]$IDjoueur, estDiff = newres)
    if(i==1)
      p = ggplot(DT,aes(x=difficulty,y=estDiff)) + geom_path(alpha = 0.2) + xlim(0,1) + ylim(0,1)
    else
      p = p + geom_path(x=DT$difficulty,y=DT$estDiff, alpha = 0.2,size=1.2)
  }
  
  DTLevel = DTLevel[order(abs(niveau))];
  joueurMed = DTLevel[1]$IDjoueur
  #DTLevel = DTLevel[order(niveau)];
  #joueurMin = DTLevel[1]$IDjoueur
  #joueurMax = DTLevel[nrow(DTLevel)]$IDjoueur
  level.sd = sd(DTLevel$niveau) 
  level.mean = mean(DTLevel$niveau) 
  DTLevel = DTLevel[order(abs(niveau - (level.mean - level.sd)))];
  joueurMin = DTLevel[1]$IDjoueur
  DTLevel = DTLevel[order(abs(niveau - (level.mean + level.sd)))];
  joueurMax = DTLevel[1]$IDjoueur
  
  
  sample = data.frame(difficulty=seq(0, 1, 0.05),IDjoueur=joueurMed)
  newres = predict(fit, newdata = sample, type = "response")
  DT = data.table(difficulty=seq(0, 1, 0.05),IDjoueur = joueurMed, estDiff = newres)
  p = p + geom_path(x=DT$difficulty,y=DT$estDiff,color="blue",size=1.3)
  
  sample = data.frame(difficulty=seq(0, 1, 0.05),IDjoueur=joueurMin)
  newres = predict(fit, newdata = sample, type = "response")
  DT = data.table(difficulty=seq(0, 1, 0.05),IDjoueur = joueurMin, estDiff = newres)
  p = p + geom_path(x=DT$difficulty,y=DT$estDiff,color="red",size=1.01)
  
  sample = data.frame(difficulty=seq(0, 1, 0.05),IDjoueur=joueurMax)
  newres = predict(fit, newdata = sample, type = "response")
  DT = data.table(difficulty=seq(0, 1, 0.05),IDjoueur = joueurMax, estDiff = newres)
  p = p + geom_path(x=DT$difficulty,y=DT$estDiff,color="red",size=1.01)
  
  print(p)
}

plot.objective.diff.curves <- function (DT) {
 
  # DTPlayers = unique(DT$IDjoueur)
  # p = ggplot()
  # for(i in 1:length(DTPlayers)){
  #   diff = DT[IDjoueur == DTPlayers[i]]$obj.diff
  #   step = DT[IDjoueur == DTPlayers[i]]$action_de_jeu
  #   df = data.frame(x1=nbSteps,y1=diff)
  #   p<-p+geom_step(aes(x1,y1),df,alpha=0.4)
  # }
  
  p <- ggplot(DT, aes(action_de_jeu, obj.diff)) + geom_bin2d(binwidth=c(1,0.05))
  print(p)
}
```

##Modeling objective difficulty for motor task

```{r modeling.difficulty.motor, echo=FALSE}
#------------------------------------------------------
#        MODELING OBJECTIVE DIFFICULTY MOTOR TASK
#------------------------------------------------------
  fit.diff.motor <- model.objective.diff(DTM)
  DTM <- add.diff.obj(DTM,fit.diff.motor)
  DTM <- add.levels(DTM,fit.diff.motor)
  print.objective.diff.model(DTM,fit.diff.motor)
  plot.objective.diff.model.curves(DTM,fit.diff.motor)
  plot.objective.diff.curves(DTM)
```

##Modeling objective difficulty for sensory task

```{r modeling.difficulty.sensory, echo=FALSE}
#------------------------------------------------------
#        MODELING OBJECTIVE DIFFICULTY SENSORY TASK
#------------------------------------------------------
  fit.diff.senso <- model.objective.diff(DTS)
  DTS <- add.diff.obj(DTS,fit.diff.senso)
  DTS <- add.levels(DTS,fit.diff.senso)
  print.objective.diff.model(DTS,fit.diff.senso)
  plot.objective.diff.model.curves(DTS,fit.diff.senso)
  plot.objective.diff.curves(DTS)
```
##Modeling objective difficulty for logical task

```{r modeling.difficulty.logical, echo=FALSE}
#------------------------------------------------------
#        MODELING OBJECTIVE DIFFICULTY LOGICAL TASK
#------------------------------------------------------
  fit.diff.logic <- model.objective.diff(DTL)
  DTL <- add.diff.obj(DTL,fit.diff.logic)
  DTL <- add.levels(DTL,fit.diff.logic)
  print.objective.diff.model(DTL,fit.diff.logic)
  plot.objective.diff.model.curves(DTL,fit.diff.logic)
  plot.objective.diff.curves(DTL)
```

```{r modeling.difficulty.merge, echo=FALSE}  
#------------------------------------------------------
#       MERGE INTO DTALL
#------------------------------------------------------
DTAll <- data.table()
DTAll <- rbind(DTAll,DTL)
DTAll <- rbind(DTAll,DTM)
DTAll <- rbind(DTAll,DTS)
```

```{r modeling.subjective.difficulty, echo=FALSE}   
#------------------------------------------------------
#        MODELING SUBJECTIVE DIFFICULTY 
#------------------------------------------------------
#evaluating confidence as a damped over time sum of win and fails;
#each win and fail importance based on objective difficulty at that time
id = DTAll$IDjoueur; # tmp vector faster to read
cur.confidence = 0;
cur.confidence.liss = 0;
lastID <- id[1];
est.confidence <- numeric(nrow(DTAll))
est.confidence[1] = 0;
obj.diff = DTAll$obj.diff
alpha <- 0.9
i = 1
for(i in 2:nrow(DTAll)){
  if(id[i] != lastID){
    cur.confidence.liss = 0;
  }else{
    if(gagnant[i-1]){
      cur.confidence = obj.diff[i-1];
    }else{
      cur.confidence = -(1 - obj.diff[i-1]);
    }
    cur.confidence.liss <- alpha * cur.confidence.liss + cur.confidence;
  }
  lastID <- id[i];
  est.confidence[i] <- cur.confidence.liss;
}

DTAll$est.confidence = est.confidence;
DTAll$est.confidence.norm = exp(DTAll$est.confidence) / (1+exp(DTAll$est.confidence));

#update DTM DTS and DTL
DTM <- DTAll[which(DTAll$nom_du_jeu=="Motrice"),]
DTL <- DTAll[which(DTAll$nom_du_jeu=="Logique2"),]
DTS <- DTAll[which(DTAll$nom_du_jeu=="Sensoriel"),]
```

```{r plot.subjective.difficulty, echo=FALSE}   
#------------------------------------------------------
#         SHOWING SUBJECTIVE DIFFICULTY 
#------------------------------------------------------

plot.subjective.difficulty <- function(DT){
  
  # Lien entre mise normalisée et difficultée estimée (hard / easy effect)
  subj.diff.med = numeric(10)
  obj.diff.bin = numeric(10)
  obj.diff.bin.cur = 0;
  test.pvals = numeric(10)
  conf.min = numeric(10)
  conf.max = numeric(10)
  nb.vals = numeric(10)
  delta.obj.subj = numeric(10)
  
  for(i in 1:10){
    obj.diff.bin.cur = round(i/10,1)
    subj.diff = 1 - DT[round(obj.diff,1)==obj.diff.bin.cur]$miseNorm;
    obj.diff.bin[i] = obj.diff.bin.cur
    subj.diff.med[i] = NA
    test.pvals[i] = NA
    conf.min[i] = NA
    conf.max[i] = NA
    delta.obj.subj[i] = NA
    nb.vals[i] = length(subj.diff)
    if(nb.vals[i] > 1){
      try.res = try(test.res <- wilcox.test(subj.diff,mu = obj.diff.bin.cur,conf.int=T))
      if (class(try.res) != "try-error"){
        test.pvals[i] = format.pval.stars(test.res$p.value)
        subj.diff.med[i] = test.res$estimate
        conf.min[i] = test.res$conf.int[1]
        conf.max[i] = test.res$conf.int[2]
        delta.obj.subj[i] = signif(subj.diff.med[i] - obj.diff.bin.cur,digit=2)
      }
    }
  }
  
  #print table of pvalues
  print(data.table(obj.diff.bin=obj.diff.bin,delta.obj.subj=delta.obj.subj,n=nb.vals,pval=test.pvals))
  
  DTPlot = data.table(obj.diff=obj.diff.bin,subj.diff=subj.diff.med)
  p = ggplot(DTPlot, aes(obj.diff,subj.diff)) +
        geom_point(alpha = 0.4, size = 3.5) +
        xlim(0,1)+
        ylim(0,1)+
        geom_errorbar(aes(ymin=conf.min, ymax=conf.max), width=.01,color="red")  +
        geom_abline(intercept = 0, slope = 1, color="blue")
  print(p)
}
```

## Subjective difficulty for Motor task

```{r plot.subjective.difficulty.motor, echo=FALSE}
plot.subjective.difficulty(DTM)
```
## Subjective difficulty for Sensory task

```{r plot.subjective.difficulty.sensory, echo=FALSE}
plot.subjective.difficulty(DTS)
```
## Subjective difficulty for Logical task

```{r plot.subjective.difficulty.logical, echo=FALSE}
plot.subjective.difficulty(DTL)
```


```{r modeling.difficulty.test, echo=FALSE}   

DT = DTM


```

